---
project_name: archsugar-cli

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "-s -w -X 'cmd.version={{ .Version }}' -X 'cmd.commit={{ .Commit }}' -X 'cmd.date={{ .Date }}'"
    binary: archsugar

archives:
  - wrap_in_directory: true

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
