name: Go

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev, master ]
  # nightly builds @3am, on latest commit to default branch == 'dev'
  schedule:
    - cron: "0 3 * * *"

env:
  GO111MODULE: on

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Test
      run: make test
    - name: SonarCloud Scan
      if: ${{ github.event_name == 'pull_request' }}
      uses: SonarSource/sonarcloud-github-action@v1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
